name: release
permissions:
  contents: write
  packages: write

on:
  push:
    tags:
      - 'v[0-9]*.[0-9]*.[0-9]*'
  workflow_dispatch:

jobs:
  publish:
    name: release-package
    runs-on: ubuntu-latest

    env:
      KEY_ID: ${{ secrets.KEY_ID }}
      SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
      PASSWORD: ${{ secrets.GPG_PASS }}
      MAVEN_CENTRAL_USER: ${{ secrets.MAVEN_CENTRAL_USER }}
      MAVEN_CENTRAL_PASS: ${{ secrets.MAVEN_CENTRAL_PASS }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26d
          add-to-path: false

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.24.5'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle clean
        run: ./gradlew clean

      - name: Publish to Maven Central
        run: ./gradlew publishAggregationToCentralPortal

      # Extract tag version (e.g. v1.6.1)
      - name: Extract version from tag
        id: vars
        run: echo "version=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"

      # Update README.md with new version
      - name: Update version in README.md
        run: |
          VERSION=${{ steps.vars.outputs.version }}
          VERSION=${VERSION#v}
          sed -i "s/implementation(\"com.zaneschepke:amneziawg-android:[^\"]*\")/implementation(\"com.zaneschepke:amneziawg-android:$VERSION\")/" README.md

      # Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Published library version ${{ github.ref_name }} to Maven Central."
